services:
  - name: esgi-nodejs-app
    type: web
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    region: frankfurt
    branch: main
    envVars:
      - key: DATABASE_URL
        fromDatabase: 
          name: esgi-nodejs-db
          property: connectionString

databases:
  - name: esgi-nodejs-db
    plan: free
    region: frankfurt
    